version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sellerapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sellerapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    container_name: sellerapi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgres_data:
  redis_data:
