name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 142.93.187.179 >> ~/.ssh/known_hosts

    - name: Add DigitalOcean droplet to known_hosts
      run: |
        ssh-keyscan -H 142.93.187.179 >> ~/.ssh/known_hosts

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        ssh root@142.93.187.179 "cd /home/deploy && git pull origin main && npm install && pm2 restart all"
